dishを追加した
H37kouya/miya-meshi pull request #186
Opened 2021-01-07 15:01 UTC by Ebi-web

Dishの移行を追加

2021-01-07 15:03 UTC, H37kouya commented
@Ebi-web 
`UpdateShopController`にも同じ処理を書いて、dishを更新できるようにしてほしい！

2021-01-10 12:10 UTC, H37kouya requested changes
`POST /shop`, `PUT /shop/{id}` で `PeriodOfTime` を保存できるようにしたい！

2021-01-10 12:10 UTC, H37kouya commented on backend/app/Usecases/CreateShopUsecase.php
> +}
これは廃止してもいいかな。

2021-01-10 12:10 UTC, H37kouya commented on backend/app/Usecases/CreateShopUsecase.php
> +}
`use App\Repositories\CreateShopRepository;` に修正が必要そう。

2021-01-10 12:10 UTC, H37kouya commented on backend/database/migrations/2020_12_07_183313_create_shop_information_table.php
> +            $table->enum('period_of_time', $this->PeriodOfTime)->nullable()->comment('時間帯');
Good!!

2021-01-10 12:10 UTC, H37kouya commented on backend/app/Http/Controllers/Api/Admin/Shop/RegisterShopController.php
> +        $this->_registerperiodoftime = $registerperiodoftime;
このコントローラーも廃止してよさそう。
あと、PHPは1ファイル1クラスを原則にしたほうがいいよ！

2021-01-10 12:10 UTC, H37kouya commented on backend/app/Enum/PeriodOfTime.php
> +        }
Good!

2021-01-12 08:37 UTC, Ebi-web commented on backend/app/Usecases/CreateShopUsecase.php
> +}
これは既に1月11日のミーティングで行われた修正のことでしょうか？

2021-01-12 08:37 UTC, Ebi-web commented on backend/app/Http/Controllers/Api/Admin/Shop/RegisterShopController.php
> +        $this->_registerperiodoftime = $registerperiodoftime;
修正pushしておきました！

2021-01-15 11:52 UTC, H37kouya requested changes

2021-01-15 11:52 UTC, H37kouya commented on backend/app/Http/Controllers/Api/Admin/Shop/UpdateShopController.php
> +        $this->_connectshopandfirebasedishusecase;
なんかこれ怪しいけど、動いた？

2021-01-15 11:52 UTC, H37kouya commented on backend/app/Http/Controllers/Api/Admin/Shop/UpdateShopController.php
> +        $this->_connectshopandfirebasedishusecase;
変数名をキャメルケースにしてほしい。

// before
`_connectshopandfirebasedishusecase`

// after
`_connectShopandFirebaseDishUsecase`

2021-01-15 11:57 UTC, H37kouya commented on backend/app/Usecases/CreateShopUsecase.php
> +}
よさそうです！そうです！

2021-01-15 12:04 UTC, H37kouya commented on backend/app/Http/Controllers/Api/Admin/Shop/RegisterShopController.php
> +                'firebase_dish_ids'              => $firebaseDishIds,
`UpdateShopController` にもこの L80行目の処理ほしいかも。

2021-01-15 12:35 UTC, H37kouya approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/101941)

2021-01-15 12:35 UTC, merged