importFirebaseShop.phpwo
H37kouya/miya-meshi pull request #193
Opened 2021-01-30 08:40 UTC by Ebi-web

2021-01-30 08:45 UTC, Ebi-web commented on backend/app/Console/Commands/importFirebaseShop.php
> +                switch ($shopinfos["priceRange"]) {
このcase群に使われている値段区分なんですが，jsonファイルでは1000円や1,000円,または~の前後にスペースが入っているかなど表記にゆれがあったので要確認です。どこかに静的プロパティとして持ってたりしますか...?

2021-02-06 11:05 UTC, H37kouya requested changes

2021-02-06 11:05 UTC, H37kouya commented on backend/app/Http/Controllers/Api/Client/Shop/FetchInstaController.php
> +>>>>>>> f25f00adf8b81eed939b953a95cc16e580037081
ここ変になってるよ？直して欲しいです 🙏

2021-02-06 11:05 UTC, H37kouya commented on backend/app/Enum/importFirebasePeriodOfTime.php
> +class importFirebasePeriodOfTime extends PeriodOfTime
これ作成しないでよさそう。、直接 `PeriodOfTime`をつかってよい。

2021-02-06 11:05 UTC, H37kouya commented on backend/app/Console/Commands/importFirebaseShop.php
> +                ShopInformationModel::period_of_time => importFirebasePeriodOfTime::arr_to_string($shopinfos["time_zone"]),
> ShopInformationModel::period_of_time => importFirebasePeriodOfTime::arr_to_string($shopinfos["time_zone"]),

これ直接 `PeriodOfTime`を使うか、何か特別な処理が必要だったら、このクラスにプライベート関数を作って良さそう

2021-02-06 11:05 UTC, H37kouya commented on backend/app/Console/Commands/importFirebaseShop.php
> +class importFirebaseShop extends Command
PHPのクラスは大文字から始めるルールがあります!

`ImportFirebaseShop`にする

2021-03-14 13:03 UTC, H37kouya approved these changes
![LGTM](https://image.lgtmoon.dev/91628)

2021-03-14 13:03 UTC, merged